config/routes.rb
Rails.application.routes.draw do
  root 'page#home'

  devise_for :users
  

   get '/cart' => 'cart#index'
   get '/cart/clear' => 'cart#clearCart'
   get '/cart/:id' => 'cart#add'
  
  get 'page/home'

  get 'page/about'
  get 'page/thanks'

  get 'page/shipping'

  get 'page/contact'
  
 resources :items 

end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :set_cart_details
    def set_cart_details
    cart = session[:cart]
    @total_price = 0
    
    if(cart)
    @total_items = session[:cart].size
    cart.each do| id, quantity|
    item = Item.find_by_id(id)
    @total_price += quantity * item.price
  end
    
  else
    @total_items = 0
    end 
end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  before_action :authenticate_user!, only: [:add]
  def add
    id = params[:id]
      # if the cart has already been created, use the existing cart else create a new cart
      if session[:cart] then
         cart = session[:cart]
      else
         session[:cart] = {}
         cart = session[:cart]
      end
      # if the product has alreadd been added to the cart, increment the value else set the value to 1
      if cart[id] then
         cart[id] = cart[id] + 1
      else
         cart[id] = 1
      end
    redirect_to :action => :index
  end #end add method

def clearCart
   session[:cart] = nil
   redirect_to :action => :index
end

def index
# if there is a cart, pass it to the page for display else pass an empty value
    if session[:cart] then
      @cart = session[:cart]
  else
    @cart = {}
  end
end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
   
  before_action :authenticate_user!, only: [:edit]
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
    
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:category, :name, :description, :price, :imageurl)
    end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
 # before_action :authenticate_user!, only: [:contact, :about]
 
  def home
  end

  def about
  end

  def shipping
  end

  def contact
  end
  
  def thanks
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/cart/index.html.erb
<h1>Your Cart</h1>

<% if @cart.empty? %>
    <p>Your Cart is empty.</p>
<% end %>

<% total = 0 %>

<table class="cart">
    <tr>
        <td class="legend"><h3>Image</h3></td>
        <td class="legend"><h3>Item</h3></td>
        <td class="legend"><h3>Price</h3></td>
        <td class="legend"><h3>Qty</h3></td>
        <td class="legend"><h3>Total</h3></td>
    </tr>


<% @cart.each do | id, quantity | %>
    <% item = Item.find_by_id(id) %>
    <tr>
        <td>
            <div class="image">
                <%= link_to (image_tag item.imageurl, :style => "height:40px"), item %>
            </div>
        </td>
        <td class="title"><%= link_to item.name, item %></td>
        <td class="price"><%= number_to_currency(item.price) %></td>
        <td class="quantity"><%= quantity %><br /></td>
        <td class="price">
        <%= number_to_currency(quantity * item.price, :unit => "€") %>
    </td>
    </tr>
    <% total += quantity * item.price %>
<% end %>


    <tr>
        <td colspan="4">
            <div class="total"><h3>Total:</h3></div>
        </td>
        <td>
            <div class="price"><h3><%= number_to_currency(total, :unit => "€") %></h3></div>
        </td>
    </tr>
</table>
<%= link_to 'Empyt the cart', cart_clear_path, id: "ecart" %>
<p>
     <%= link_to 'Continue Shopping', :controller => :items %>
      <%= link_to 'check out', page_thanks_path %>
</p>

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :imageurl %><br>
    <%= f.text_field :imageurl %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1  id="list_item">Listing Items</h1>



<ul id="product_list">
  
    <% @items.each do |item| %>
     
    <li>    
       
       
       
       
  <%#= item.category %>
        <%= link_to (image_tag item.imageurl), item %>
        
        
        <br>
       <h1> <%= item.name %></h1> <br>
       <p> <%= item.description %></p>
       <h3>€ <%= item.price %></h3>
        
        
        
        <div id="links">
        <%= link_to 'Show', item %>
        <%#= link_to 'Edit', edit_item_path(item) %>
        <%#= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %>
        <a href="/cart/<%= item.id %>">Add to Cart</a>
        </div>
   
   </li>
    <% end %>
 
</ul>
<br>

<%#= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @item.category %>
</p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<p>
  <strong>Imageurl:</strong>
  <%= @item.imageurl %>
</p>

<%#= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ClisteWatch</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
<div id="main">
  <img src="/assets/BookHeader.jpg"  width="100%" alt="head" id="top_img">
    <ul id="main_nav">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", page_about_path %></li>
      <li><%= link_to "Products", items_path %></li>
      <li><%= link_to "Shipping", page_shipping_path %></li>
      <li><%= link_to "Contact", page_contact_path  %></li>
      <li><a href="/cart">Cart(<%=@total_items%>,€<%=@total_price%>)</a> </li>
      <% if user_signed_in? %>
      <li><%= link_to "SignOut", destroy_user_session_path, :method => :delete %></li>
      <% else %>
         <li><%= link_to "SignIn", new_user_session_path %></li>
        <li> <%= link_to "SignUp", new_user_registration_path %></li>
    <% end %>
    </ul>
  
  <%= yield %>
  
  
<div id="footer"><h2>ClisteWatche </h2></div>

</div>

</body>
</html>

app/views/page/about.html.erb
<div id="about_container">
  <div id-"about_describtion">
    <br><br>
    <h1>ClisteWatch:</h1><br><br>
    <h4>We are the best company :-)</h4>
    
  </div>
  
</div>

app/views/page/contact.html.erb
<br>
<div id="contact_inf">
  <h1>Smart watch: </h1><br>
<h4>105 LarkHill Road</h4>
<h4>Whitehall</h4>
<h4>Dublin</h4>
<div id="map_photo"><img src="/assets/map.PNG" ali="fined us" width="100%" ></div>
</div>
<form id="contact_form" action="#" method="POST" enctype="multipart/form-data">
	<div class="row">
		<label for="name">Your name:</label><br />
		<input id="name" class="input" name="name" type="text" value="" size="30" /><br />
	</div>
	<div class="row">
		<label for="email">Your email:</label><br />
		<input id="email" class="input" name="email" type="text" value="" size="30" /><br />
	</div>
	<div class="row">
		<label for="message">Your message:</label><br />
		<textarea id="message" class="input" name="message" rows="7" cols="30"></textarea><br />
	</div>
	<input id="submit_button" type="submit" value="Send email" />
</form>						

app/views/page/home.html.erb
<br><h1 id="home_title">Welcome to ClisteWatch </h1>

<!==============Vedio code==================> 
       <div class="container">
  <br><br><br><br>
<div class="embed-responsive embed-responsive-16by9">
    <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/nhm_lt6XTno"></iframe>
</div>
    </div>
    
  

      <!================================>
      
      

app/views/page/shipping.html.erb
<h1>shipping</h1>
<p>Want to track your package?</p>

app/views/page/thanks.html.erb
<h1>thank you</h1>